### ISSUE TITLE
It does not get the end of the translated file, IndexError: list index out of range

### ISSUE THREAD

**Issue by toprak** [sinedie/SRTranslator#10]
Everything was okay, in last 500 character it pasted original text and translation shown there were no problem at all but srtranslator gave that error, everything was ok according to ur conditions.
``` Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/toprak/.local/lib/python3.10/site-packages/srtranslator/__main__.py", line 81, in <module>
    srt.translate(translator, args.src_lang, args.dest_lang)
  File "/home/toprak/.local/lib/python3.10/site-packages/srtranslator/srt_file.py", line 145, in translate
    subs_slice[i].content = translation[i]
IndexError: list index out of range
```

**Comment by sinedie** [comment]
Could you hand me the subtitle file? I can't replicate. Ty

**Comment by toprak** [comment]
@sinedie [here](https://we.tl/t-AhU76443DZ)

**Comment by sinedie** [comment]
Can't replicate, sry. I could do an improved error handling tho.

Already uploaded to [PyPi](https://pypi.org/project/srtranslator/).

**Comment by toprak** [comment]
that would be good at least we could find a way, thanks what should I do close this or?

**Comment by toprak** [comment]
still no updates?

**Comment by sinedie** [comment]
@toprak No luck, can't replicate :/

**Comment by toprak** [comment]
@sinedie even though u could not replicate, let it open maybe someone would

**Comment by toprak** [comment]
@sinedie I asked chatgpt to help :D maybe it would help

```
It seems like you're encountering an "IndexError: list index out of range" error in the code for the srtranslator library. This error is raised when you're trying to access an element in a list using an index that's out of the range of the list.

In the code provided, it looks like the error is occurring in the following line:

css
Copy code
subs_slice[i].content = translation[i]
This error is likely being caused because the length of the translation list is different from the length of the subs_slice list. To resolve this issue, you should check the lengths of both lists before performing this operation and make sure that they're the same. You could do this by adding the following code before the operation:

scss
Copy code
if len(translation) != len(subs_slice):
    raise IndexError("Translation and subs slice lists have different lengths.")
This will raise an error with a more descriptive message, which will help you understand what's going wrong in the code.

```

**Comment by sinedie** [comment]
Hey, yeah, I know where should be the error but for the script to know if the translation is done the number of sentences should be equal in source and destination. Look this on line 104 : https://github.com/sinedie/SRTranslator/blob/84cad275b1472a08d905a9907e623ff707ed44af/srtranslator/translators/deepl.py#L100-L106

So, if a subtitle has 10 dialogs, it translate 10 dialogs, but somehow you are getting more?? Again, couldn't reproduce even with your example :/

Maybe you could add some prints statements to check what response are you getting?

**Comment by toprak** [comment]
@sinedie i lost the subtitle if you have can you send me? also dunno how to add some print statements

**Comment by sinedie** [comment]
@toprak Don't have it anymore :/.

It keeps being an issue with other ones that you had translated?

**Comment by toprak** [comment]
@sinedie it just was happening on that series weirdly iirc, I formatted my pc I will be at home like 2 days later so will test it on another series :(
