### ISSUE TITLE
Error Timed out trying to get element

### ISSUE THREAD

**Issue by erickgamer787** [sinedie/SRTranslator#12]
Hello, I noticed that in the last version using your example script it sometimes gives the error = Timed out trying to get element (XPATH = /html/body/div[11]/div/div/div/div/div[2]/button),
sometimes it works, other times it gives this error and stops the whole script, I have a suggestion in the recursive system, put a parameter that if the translation fails because of the proxy or something else, it will be retentive at least twice. 
![screnshot](https://user-images.githubusercontent.com/61727583/213920823-b5298cd2-608e-42a5-886f-78e87fab04de.png)

**Comment by sinedie** [comment]
It was a optional dialog that sometimes won't show up, sometimes it does. Implemented in the last week by deepl. Should be fixed in v0.1.71. And it is already in [PyPi](https://pypi.org/project/srtranslator/).

Please close it if solves the issue (couldn't test it too much)

**Comment by toprak** [comment]
it does not work on my end too @sinedie 
```Timed out trying to get element (XPATH = //button[@dl-test='translator-lang-option-en'] | //button[text()='English'])
```

**Comment by erickgamer787** [comment]
hello I tested again with the new update but now in the 4th translation it is giving this error
![screnshot2](https://user-images.githubusercontent.com/61727583/213953616-362ec538-6a57-4478-8f8e-98bfc613b55f.png)

**Comment by sinedie** [comment]
@erickgamer787 I guess it is working now?
@toprak That's another issue, could you create it if persists? ty
