### ISSUE TITLE
SRTranslator stopped working.

### ISSUE THREAD

**Issue by Trixster-dk** [sinedie/SRTranslator#17]
A few days ago it was working fine, but now i get 0% and stops after 1-2 min with no error.
Tried to update all my libraries but still the same.

Translating xtest.en.srt to xtest.da.srt
Loading c:\serier\xtest.en.srt
... Translating chunk. 0 %

Code 
def translate_file(file_path, translated_file, src_lang, dst_lang):
    try:
        translator = DeeplTranslator()
        srt = SrtFile(file_path)
        srt.translate(translator, src_lang, dst_lang)
        srt.wrap_lines(32)
        srt.save(translated_file)
        translator.quit()
    except Exception as e:
        log.log_error(f"Error during translation: {str(e)}")
END.

Did run it with DEBUG on. and here is the log file.
06-02-2023 13:43:09 Translating xtest.en.srt to xtest.da.srt
06-02-2023 13:43:09 Getting a new Proxy from https://www.sslproxies.org/
06-02-2023 13:43:09 Starting new HTTPS connection (1): www.sslproxies.org:443
06-02-2023 13:43:09 https://www.sslproxies.org:443 "GET / HTTP/1.1" 200 None
06-02-2023 13:43:09 Starting new HTTP connection (1): 134.122.26.11:80
06-02-2023 13:43:09 Starting new HTTP connection (1): 167.71.199.211:39909
06-02-2023 13:43:10 Starting new HTTP connection (1): 103.169.7.88:61524
06-02-2023 13:43:10 Starting new HTTP connection (1): 66.70.178.214:9300
06-02-2023 13:43:11 http://66.70.178.214:9300 "GET http://www.google.com/ HTTP/1.1" 503 None
06-02-2023 13:43:11 Starting new HTTP connection (1): 140.227.25.191:23456
06-02-2023 13:43:11 Starting new HTTP connection (1): 198.27.74.6:9300
06-02-2023 13:43:12 Starting new HTTP connection (1): 158.69.52.218:9300
06-02-2023 13:43:12 Starting new HTTP connection (1): 43.243.126.35:3128
06-02-2023 13:43:13 Starting new HTTP connection (1): 5.45.92.167:443
06-02-2023 13:43:13 Starting new HTTP connection (1): 51.159.115.233:3128
06-02-2023 13:43:14 http://51.159.115.233:3128 "GET http://www.google.com/ HTTP/1.1" 302 347
06-02-2023 13:43:14 http://51.159.115.233:3128 "GET http://www.google.com/sorry/index?continue=http://www.google.com/&q=EgQzn59JGOfrg58GIinkVaBV1pS1VN4PxT2B8EabTJ-M6KttDyAsL6nE6VI8xdTOvK16iHVVyjIBcg HTTP/1.1" 429 3030
06-02-2023 13:43:14 Creating Selenium Webdriver instance
06-02-2023 13:43:14 driver not found in PATH, trying Selenium Manager
06-02-2023 13:43:14 Executing: C:\Users\Trixster\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\common\windows\selenium-manager.exe --browser firefox
06-02-2023 13:43:14 Using driver at: C:\Users\Trixster\.cache\selenium\geckodriver\win64\0.32.1\geckodriver.exe
06-02-2023 13:43:14 Started executable: `geckodriver` in a child process with pid: 2804
06-02-2023 13:43:15 POST http://localhost:64112/session {"capabilities": {"firstMatch": [{}], "alwaysMatch": {"browserName": "firefox", "acceptInsecureCerts": true, "moz:debuggerAddress": true, "pageLoadStrategy": "normal"}}}
06-02-2023 13:43:15 Starting new HTTP connection (1): localhost:64112
06-02-2023 13:43:18 http://localhost:64112 "POST /session HTTP/1.1" 200 793
06-02-2023 13:43:18 Remote response: status=200 | data={"value":{"sessionId":"d318d2f9-78db-4a95-a80d-cdd9901442b6","capabilities":{"acceptInsecureCerts":true,"browserName":"firefox","browserVersion":"109.0.1","moz:accessibilityChecks":false,"moz:buildID":"20230127170202","moz:debuggerAddress":"127.0.0.1:64113","moz:geckodriverVersion":"0.32.1","moz:headless":true,"moz:platformVersion":"10.0","moz:processID":26220,"moz:profile":"C:\\Users\\Trixster\\AppData\\Local\\Temp\\rust_mozprofileCWRELt","moz:shutdownTimeout":60000,"moz:useNonSpecCompliantPointerOrigin":false,"moz:webdriverClick":true,"moz:windowless":false,"pageLoadStrategy":"normal","platformName":"windows","proxy":{},"setWindowRect":true,"strictFileInteractability":false,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000},"unhandledPromptBehavior":"dismiss and notify"}}} | headers=HTTPHeaderDict({'content-type': 'application/json; charset=utf-8', 'cache-control': 'no-cache', 'content-length': '793', 'date': 'Mon, 06 Feb 2023 12:43:17 GMT'})
06-02-2023 13:43:18 Finished Request
06-02-2023 13:43:18 POST http://localhost:64112/session/d318d2f9-78db-4a95-a80d-cdd9901442b6/window/maximize {}
06-02-2023 13:43:18 http://localhost:64112 "POST /session/d318d2f9-78db-4a95-a80d-cdd9901442b6/window/maximize HTTP/1.1" 200 49
06-02-2023 13:43:18 Remote response: status=200 | data={"value":{"x":4,"y":4,"width":1366,"height":768}} | headers=HTTPHeaderDict({'content-type': 'application/json; charset=utf-8', 'cache-control': 'no-cache', 'content-length': '49', 'date': 'Mon, 06 Feb 2023 12:43:18 GMT'})
06-02-2023 13:43:18 Finished Request
06-02-2023 13:43:18 Going to https://www.deepl.com/translator
06-02-2023 13:43:18 POST http://localhost:64112/session/d318d2f9-78db-4a95-a80d-cdd9901442b6/url {"url": "https://www.deepl.com/translator"}
06-02-2023 13:43:20 http://localhost:64112 "POST /session/d318d2f9-78db-4a95-a80d-cdd9901442b6/url HTTP/1.1" 200 14
06-02-2023 13:43:20 Remote response: status=200 | data={"value":null} | headers=HTTPHeaderDict({'content-type': 'application/json; charset=utf-8', 'cache-control': 'no-cache', 'content-length': '14', 'date': 'Mon, 06 Feb 2023 12:43:18 GMT'})
06-02-2023 13:43:20 Finished Request
06-02-2023 13:43:20 POST http://localhost:64112/session/d318d2f9-78db-4a95-a80d-cdd9901442b6/element {"using": "css selector", "value": "[aria-label=Close]"}
06-02-2023 13:43:20 http://localhost:64112 "POST /session/d318d2f9-78db-4a95-a80d-cdd9901442b6/element HTTP/1.1" 404 414
06-02-2023 13:43:20 Remote response: status=404 | data={"value":{"error":"no such element","message":"Unable to locate element: [aria-label=Close]","stacktrace":"RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\nWebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:180:5\nNoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:392:5\nelement.find/</<@chrome://remote/content/marionette/element.sys.mjs:275:16\n"}} | headers=HTTPHeaderDict({'content-type': 'application/json; charset=utf-8', 'cache-control': 'no-cache', 'content-length': '414', 'date': 'Mon, 06 Feb 2023 12:43:20 GMT'})
06-02-2023 13:43:20 Finished Request
06-02-2023 13:43:20 POST http://localhost:64112/session/d318d2f9-78db-4a95-a80d-cdd9901442b6/element {"using": "css selector", "value": "[aria-label=Close]"}
06-02-2023 13:43:20 http://localhost:64112 "POST /session/d318d2f9-78db-4a95-a80d-cdd9901442b6/element HTTP/1.1" 404 414
06-02-2023 13:43:20 Remote response: status=404 | data={"value":{"error":"no such element","message":"Unable to locate element: [aria-label=Close]","stacktrace":"RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\nWebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:180:5\nNoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:392:5\nelement.find/</<@chrome://remote/content/marionette/element.sys.mjs:275:16\n"}} | headers=HTTPHeaderDict({'content-type': 'application/json; charset=utf-8', 'cache-control': 'no-cache', 'content-length': '414', 'date': 'Mon, 06 Feb 2023 12:43:20 GMT'})
06-02-2023 13:43:20 Finished Request
06-02-2023 13:43:21 POST http://localhost:64112/session/d318d2f9-78db-4a95-a80d-cdd9901442b6/element {"using": "css selector", "value": "[aria-label=Close]"}
06-02-2023 13:44:32 Finished Request
06-02-2023 13:44:34 Error during translation: Translation timed out

**Comment by KryptoST** [comment]
The same thing happens to me too, I'm using the latest version.

**Comment by KryptoST** [comment]
srt_file.py, line 138, in translate
    translation = translator.translate(
deepl.py, line 125, in translate
    raise TimeOutException("Translation timed out")
srtranslator.translators.base.TimeOutException: Translation timed out

**Comment by KryptoST** [comment]
![image](https://user-images.githubusercontent.com/30755854/217043812-99601c72-1c18-484b-8cd3-dfdbedc10672.png)
I think I found something in the source field does not write anything

**Comment by Trixster-dk** [comment]
Using latest version. 0.1.81 :-)

**Comment by ab-unstable** [comment]
Same issue here, it stays some seconds on "Translating chunk. 0 %" and then throws a timeout error.
When running with the -s flag, I can see the deepl language settings being correctly set up in the browser, but no text input is ever pasted into the translation box.

When runnning with -vv flag, it procudes a very long log, which I attached here
[log.txt](https://github.com/sinedie/SRTranslator/files/10670733/log.txt)
.

**Comment by erickgamer787** [comment]
The same also he selects the languages but does not put the text

**Comment by sinedie** [comment]
Yeah, seems like something in DeepL's page changed and the textarea is disabled at start. Im working on a solution, hope to fix it today in the night. Don't promise anything tho.
