### ISSUE TITLE
Translation timed out

### ISSUE THREAD

**Issue by drphero** [sinedie/SRTranslator#20]
By using -s I can see that DeepL is asking to upgrade to pro in order to translate more that 5,000 characters at once. I thought SRTranslator does the translation in smaller chunks to avoid this problem. Is this a bug?

**Comment by sinedie** [comment]
Hi, sry by the late reply.

Yeah, it does, but it is not 5000, deepl downgrade it to 3000. This should be done in chunks.

Can you show me something to see if it is really a bug? A screenshot could be okay. Ty

**Comment by Vrejf** [comment]
Hi! I got something very similar. Trying on an srt with about 30k chars.
`... Translating chunk. 0 %
... Translating chunk. 9 %
... Translating chunk. 19 %
... Translating chunk. 29 %
2023-02-12 20:23:42.285 Uncaught app exception
...
    raise TimeOutException("Translation timed out")
srtranslator.translators.base.TimeOutException: Translation timed out`

**Comment by Vrejf** [comment]
Hi again! 
In selenium_utils.py the Keys.CONTROL only works on some systems (windows/linux?), so I added this code to make it work on more systems.
It solved the problem for me atleast. Im on MacOS
```
class TextArea(BaseElement):
    def write(self, value: str) -> None:
        if self.element is None:
            return
        
        # Check OS to use Cmd or Ctrl keys
        cmd_ctrl = Keys.COMMAND if sys.platform == "darwin" else Keys.CONTROL

        actions_handler = ActionChains(self.driver).move_to_element(self.element)
        # Changed key variables:
        actions_handler.click().key_down(cmd_ctrl).send_keys("a").perform()
        actions_handler.send_keys(Keys.CLEAR).key_up(cmd_ctrl).perform()
        actions_handler.send_keys(*value).perform()
```
Also don't know if chuck size should be 3000 instead of 4500 in srt_files.py?

**Comment by sinedie** [comment]
Hey, ok, first the timeout... It timesout if DeepL takes too long to translate (this is, nothing written, [...] character in result, or different number of sentences in both inputs) see [this](https://github.com/sinedie/SRTranslator/blob/84cad275b1472a08d905a9907e623ff707ed44af/srtranslator/translators/deepl.py#L100). Can you show me the browser when it timeout. Use -s flag to see it)

Second, ty for catching this, gonna update it tonight for mac users

Last, yeah it is okay, it is just the default value, it really doesn't matter to much. the real value is the one in the [translator](https://github.com/sinedie/SRTranslator/blob/9553ac64f980e342136af2729478822e3f2da038/srtranslator/srt_file.py#L130).

**Comment by Vrejf** [comment]
Using the code that I added I no longer have problems with timeout. Thank you!
