### ISSUE TITLE
DeepL developer API key?

### ISSUE THREAD

**Issue by dgoryeo** [sinedie/SRTranslator#21]
Hi @sinedie , would this script work with DeepL (free) developer API? Do I need to give my API key to the script, or any other credentials? Thanks.

**Comment by sinedie** [comment]
Hey @dgoryeo, yes!, you could make your own translator... Look at [this](https://github.com/sinedie/SRTranslator/blob/master/docs/create_translator.md#create-your-own-translator) to know how to.

As a help, I would put the API key in an enviroment variable, load it with python-dotenv and use the api as DeepL says it should be used (idk how to), and make the petitions inside the translate method of your own translator class.

Let me know if you need help, we could make a new example with it for people that want to use it the same way.

**Comment by dgoryeo** [comment]
Thanks for the quick reply. Will look at the example.

**Comment by sinedie** [comment]
@dgoryeo any update?

**Comment by dgoryeo** [comment]
I wasn't able to use the instructions in the example --I'm novice in python. I would need to learn more about how to epand exisiting modules with new classes.

Meanwhile I came across this one: https://tern.1c7.me/#/.   [thought you might be interested too.]

I can close this "issue" --would you like me to? 
Thanks again!
