### ISSUE TITLE
SRTranslatorGui

### ISSUE THREAD

**Issue by KryptoST** [sinedie/SRTranslator#25]
Hello, I made a graphical interface. Well, I tried, but the question is that it works

**Important information the progress bar is a bug so if it does not progress, do not pay attention**

[SRTranslatorGUI.zip](https://github.com/sinedie/SRTranslator/files/10777497/SRTranslatorGUI.zip)

![image](https://user-images.githubusercontent.com/30755854/219899480-f35c587e-2b36-4cb5-9b05-9e9a9b4f75d2.png)

**Comment by sinedie** [comment]
Wow!!! that's too nice. Really glad you did this.

Can you share the code? maybe a repo? (i guess C++?)

**Comment by KryptoST** [comment]
> Wow!!! that's too nice. Really glad you did this.
> 
> Can you share the code? maybe a repo? (i guess C++?)

I'll share the code tomorrow maybe there are still some bugs and it's done in c#

**Comment by KryptoST** [comment]
here is the source code is a little ugly code
[SRTranslatorGUI.zip](https://github.com/sinedie/SRTranslator/files/10777300/SRTranslatorGUI.zip)

**Comment by sinedie** [comment]
Hey, sry for the late reply... Ok... so, I saw your code, but can you make a repo?

Or maybe we could join and create a complete multiplataform GUI? (even when I dont really no C#)

**Comment by KryptoST** [comment]
I upload more than a while now I'm not on the pc

**Comment by KryptoST** [comment]
here is the repository https://github.com/KryptoST/SRTranslatorGUI

**Comment by sinedie** [comment]
Haven't tried, but really nice you did this :D

**Comment by KryptoST** [comment]
I suppose that now I will have to put the other options such as showing the browse
I also have to see how to solve the progress of the file

**Comment by sinedie** [comment]
Yeah. But really I think is overkill to do it in C#, as it can be done in python with things like easyGUI or pyQt or with js-ts in Electron, but whatever it works is ok.

Im gonna close this issue and let's keep all updates and GUI features in your repo. I can help if u want (I can learn C#)

**Comment by sinedie** [comment]
@KryptoST, I put the GUI link and credits on the readme. Hope people start using it.

**Comment by KryptoST** [comment]
hello I could not be connected because I have been sick thanks for putting the link in your credits

**Comment by KryptoST** [comment]
hay alguna manera de utilizar proxies propios hay alguien que me pidio eso

**Comment by sinedie** [comment]
Yeah, if you pass your own webdriver. However I could make another cli argument for that... Gonna try later

But pls open a new issue to keep things in order. Ty


Si, si creas vos mismo el webdriver de selenium. Tambien podria ponerlo como un argumento del cli. Ahora intento.

(Abri un nuevo issue, para que haya un registro. Gracias)

**Comment by KryptoST** [comment]
here is the interface made in python 😁

It took me 2 days and this is version two because first I was using pyqt5

https://github.com/KryptoST/SRTranslatorGUI-Python
