### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: 'geckodriver.log'

### ISSUE THREAD

**Issue by tin2tin** [sinedie/SRTranslator#28]
File "C:\Users\45239\AppData\Roaming\Python\Python310\site-packages\srtranslator\translators\deepl.py", line 60, in __init__
    self.driver = create_driver(proxy)
  File "C:\Users\45239\AppData\Roaming\Python\Python310\site-packages\srtranslator\translators\selenium_utils.py", line 48, in create_driver
    driver = webdriver.Firefox(proxy=proxy)
  File "C:\Users\45239\AppData\Roaming\Python\Python310\site-packages\selenium\webdriver\firefox\webdriver.py", line 191, in __init__
    self.service = Service(executable_path, service_args=service_args, log_path=service_log_path)
  File "C:\Users\45239\AppData\Roaming\Python\Python310\site-packages\selenium\webdriver\firefox\service.py", line 48, in __init__
    log_file = open(file, "a+", encoding="utf-8")
PermissionError: [Errno 13] Permission denied: 'geckodriver.log'

**Comment by sinedie** [comment]
That's a Selenium issue, probably your firefox install is an older version?  Check [this](https://stackoverflow.com/questions/40466809/permission-denied-geckodriver-log-while-running-selenium-webdriver-in-python)

**Comment by tin2tin** [comment]
I tried updating Firefox, same error. Strange. It worked just a few days ago.

**Comment by sinedie** [comment]
If you didn't upgraded selenium or firefox and it just stopped working, maybe you could have that file open? (I don't think so, but just in case).

**Comment by tin2tin** [comment]
I need to run Blender as admin, and then there is no error. Typically, that is only needed for installing python modules, but not in this case, I guess?

**Comment by sinedie** [comment]
It shouldn't be a problem to run without admin permissions. It really doesn't install nothing. Somehow 'geckodriver.log' file is getting open for something else while script is running or is being created with superuser role.

Maybe could be this last one. If you already have a geockodriver.log file but was created by admin it won't let you edit it with a regular user... Try to delete that file (it could be in the library folder or subtitles folder) and run the script from blender without admin. It could work, I really don't know why this is happening and can repodruce in my machine.

**Comment by tin2tin** [comment]
It seems to be working in Blender 3.6 alpha, so it might be related the version of python which comes with Blender, but I haven't digged deep into that stuff.  I'll just close this report for now.
