### ISSUE TITLE
Just a thank you

### ISSUE THREAD

**Issue by Pheggas** [sinedie/SRTranslator#32]
Thank you for this project. I was able to translate Kuciak: Vražda novinára (really great movie btw) for my parents. It was done in couple of minutes in really good quality. There were some errors in the subtitles but overall they are really great.

**Thank you!**

![2023-03-04_19-41](https://user-images.githubusercontent.com/9994511/222923314-024db55c-2c43-4293-909f-21cc3689d0cd.png)

EDIT: Added image of progress

**Comment by sinedie** [comment]
😄 Im glad people is using it, that was the whole idea 😄 . Hope you keep using it

**Comment by Pheggas** [comment]
If I get an opportunity, i definitely will!
