### ISSUE TITLE
Does this project still work?

### ISSUE THREAD

**Issue by Root-FTW** [sinedie/SRTranslator#33]
Does this project still work?

I am on windows 10 with everything perfectly installed

And I ran this command:
python -m srtranslator The.Sparring.Partner.2022.1080p.BluRay.x265.10bit-RootFTW.srt -i en -o es

This is the file I want to translate:
 The.Sparring.Partner.2022.1080p.BluRay.x265.10bit-RootFTW.srt

It's in English, and I want to translate it to Spanish.

![image](https://user-images.githubusercontent.com/108767514/225734629-d55c5044-531e-40cc-ab04-ee1289477df9.png)

**Comment by sinedie** [comment]
Yeah, it works, I mantain this project.

Ok... sometimes deepl takes a little time for translate but it can fail for a lot of reason (bad internet, get banned, weird subtitles, or maybe I mess it up somewhere).

Try running it with -s flag to see what is happening in the browser or send me the subtitle cause I can replicate the issue without more information

**Comment by Root-FTW** [comment]
> Yeah, it works, I mantain this project.
> 
> Ok... sometimes deepl takes a little time for translate but it can fail for a lot of reason (bad internet, get banned, weird subtitles, or maybe I mess it up somewhere).
> 
> Try running it with -s flag to see what is happening in the browser or send me the subtitle cause I can replicate the issue without more information

I put the subtitles here, could you try?

https://we.tl/t-AqEaMEqUYb

**Comment by sinedie** [comment]
It works normal: 
![image](https://user-images.githubusercontent.com/43920544/225802369-7f45b045-8ef9-471e-ac82-a3316a224052.png)

Maybe give it another try... or it happens no matter how much you try?

**Comment by Root-FTW** [comment]
Could you share with me, exactly how did you run it on your terminal?


for example I wrote this:
python -m srtranslator The.Sparring.Partner.2022.1080p.BluRay.x265.10bit-RootFTW.srt -i en -o es

**Comment by sinedie** [comment]
I used the same

python -m srtranslator ./The.Sparring.Partner.2022.1080p.BluRay.x265.10bit-RootFTW.srt -i en -o es

https://fromsmash.com/.MBGWbr1nd-et

**Comment by wowwoo** [comment]
At first thank you for your hard work! I love this project and I use it everyday.
But  tiny problem is... Almost all translated subtitles are mixed with untranslated sentences. It occurs regardless of the arm64 or x86 version and does not seem to be related to the language. But I love it so much thank you again!

**Comment by sinedie** [comment]
@wowwoo Thank you for using it!

Maybe DeepL won't translate some sentences.... weird, make another issue and I will investigate. Maybe put an example.

Ty again

**Comment by sinedie** [comment]
Closing due unactivity. Feel free to reopen if issue persist
