### ISSUE TITLE
Increase the delay to prevent unfinished translations

### ISSUE THREAD

**Issue by toprak** [sinedie/SRTranslator#44]
Based on my own experiences, I can say that there's a high chance of getting incomplete or patchy results when translating from English to Turkish, probably due to my insufficient internet or other resources. I think the solution might be to increase the delay slightly and I can build it locally. Just tell me which parts to change, and that should be enough.

**Comment by toprak** [comment]
![image](https://user-images.githubusercontent.com/43301560/235299095-85e3c620-8dfb-4ac0-a347-a17d77b242a5.png)
here is the example, there should be its turkish translation in bottom instead of D

**Comment by sinedie** [comment]
While I fix it, you could see [this](https://github.com/sinedie/SRTranslator/blob/master/srtranslator/translators/deepl_scrap.py#L128-L129). You could put an sleep or something similar when the translation is done.

**Comment by toprak** [comment]
I changed the def translate like this but results are the same did I something wrong? @sinedie 

```    def translate(self, text: str, source_language: str, destination_language: str):
        if source_language != self.src_lang:
            self._set_source_language(source_language)
        if destination_language != self.target_lang:
            self._set_destination_language(destination_language)

        clean_text = text.replace("[...]", "@[.]@")

        self.input_lang_from.write((clean_text))

        # Maximun number of iterations 60 seconds
        for _ in range(60):
            translation = self.input_destination_language.value

            if self._is_translated(clean_text, translation):
                time.sleep(2)
                return translation.replace("@[.]@", "[...]")
            time.sleep(1)

        self.quit()
        raise TimeOutException("Translation timed out")```

**Comment by sinedie** [comment]
You are not changing the result, just wating 2 sec for noting.

This line ```translation = self.input_destination_language.value``` should be repeated after the sleep, so it gets the current value before and after the waiting time

**Comment by toprak** [comment]
@sinedie I do not have any coding skill or history sorry about that, is that the correct?
```for _ in range(60):
        translation = self.input_destination_language.value

        if self._is_translated(clean_text, translation):
            time.sleep(2)
            translation = self.input_destination_language.value  # Repeat the line after sleep
            return translation.replace("@[.]@", "[...]")
        time.sleep(1)```

**Comment by toprak** [comment]
ah yeah, I guess I did the correct one because it seems it worked
```00:30:41,680 --> 00:30:43,630
Bu kadar depresif olma.
Don't sound so damn depressed...```

**Comment by sinedie** [comment]
yep, thats right.

**Comment by sinedie** [comment]
@toprak Gonna add this today to the code. But a question, why 2 seconds, why not 1? did you found something?

**Comment by toprak** [comment]
@sinedie no just to be sure

**Comment by toprak** [comment]
thanks for hardworks

**Comment by toprak** [comment]
@sinedie after some tests with 1 sec delay sometimes it happens again, can you increase it to 2 sec please?

**Comment by sinedie** [comment]
@toprak Done
