### ISSUE TITLE
Time out

### ISSUE THREAD

**Issue by Tommasov** [sinedie/SRTranslator#47]
I'm getting this error:
Timed out trying to get element (XPATH = //button[@data-testid='translator-lang-option-en'] | //button[text()='English'])

Any help?
Thanks

**Comment by Tommasov** [comment]
Hi, the problem only occur with DeeplTranslator(), translating to english
It worked using TranslatePy(), actually pretty fast

**Comment by sinedie** [comment]
That's the error. There is no option for translating to en. There are two options: en-US and en-GB

Check the [docs](https://github.com/sinedie/SRTranslator/blob/master/docs/deepl_scrap.md#supported-languages)
