### ISSUE TITLE
files too big

### ISSUE THREAD

**Issue by rcspam** [sinedie/SRTranslator#48]
A srt file with about 5000 lines is too big for the deepl translator ( a timeout error occures). So the possibility  to split  in several files and concat it when all files are stranslate could be a cool improvement.

**Comment by sinedie** [comment]
That would be nice... but first, do you know if it was a normal DeepL page timeout or DeepL ban the proxy IP for too many requests? (I really think it is the second and we dont need to split the file, but refresh the proxy on the driver, but need to be sure)

**Comment by rcspam** [comment]
Hello,
I had a set of more than 2500 subtitles, about. 10000 characters to
translate ( movie of more than two hours with a lot of dialogue), I was
forced to split it in two files of 5000   because Deeply was stopping at
75%, so yes I think the site banned the proxy IP because of too many
requests.

Thanx
