### ISSUE TITLE
is it possible to implement this?

### ISSUE THREAD

**Issue by toprak** [sinedie/SRTranslator#49]
Since if there is [...]on translation it wont going to next chunk so I think in the waiting phase after entering the chunk to get translation, make it click to [...] and select top option or random one it does not matter it will give its alternate translation and problem will be fixed.

**Comment by sinedie** [comment]
Ok... so you are getting timeouts cause deepl hangs in translations witth [...]? that is possible, but maybe an overkill... gonna think about it

**Comment by toprak** [comment]
yeah, thanks

**Comment by toprak** [comment]
yeah thanks, actually it is not overkill, it would be good for people that automatized their workflow so it wont disturbed

**Comment by sinedie** [comment]
Maybe the #51 PR could sove this issue. When deepl hangs, it just try changing the proxy. Maybe it hangs cause of timeout.

Gonna let it open until confirmed.

**Comment by toprak** [comment]
@sinedie I could barely test it, sorry for the late reply, I translated about 20 srt, I guess it doesn't stay in [...], even if it does, the logic of trying again with a different proxy is nice, it works very well now.
