### ISSUE TITLE
an idea about deepl

### ISSUE THREAD

**Issue by toprak** [sinedie/SRTranslator#50]
using [this](https://github.com/OwO-Network/DeepLX) with proxies probably would be more quick, what about implement this idea?

**Comment by sinedie** [comment]
Had been kind of busy but I did another built-in translator with PyDeepX, But... it gets banned and proxy won't work. Working on it.

**Comment by sinedie** [comment]
Already tried, even contribute on PyDeepX, but got banned after even one request. It is a DeepL API limitation

**Comment by toprak** [comment]
@sinedie Weird i had no prob after resetting router once this one is also fast qnd good there should be no banning on this https://github.com/eggplants/deepl-cli

**Comment by sinedie** [comment]
I just saw it and could work, but maybe won't be too fast.

1. It uses playwright (another puppeteer as selenium) with the same 3000 character limit
2. It opens and closes the browser for each request, we don't do that here.

May be worth the try, but I don't think I'll make put like a built-in translator.

There is the -untested- code if you wanna use it tho:

```python
from deepl import DeepLCLI
from srtranslator.translators.base import Translator


class DeeplCli(Translator):
    max_char = 3000

    def translate(self, text: str, source_language: str, destination_language: str):
        deepl = DeepLCLI(source_language, destination_language)
        return deepl.translate(text)
```

**Comment by toprak** [comment]
@sinedie deeplx working on me, could you find a way to use proxy?

**Comment by toprak** [comment]
@sinedie hell yeah! thanks!
