### ISSUE TITLE
deepl scraper fails on MacM1 due to malformed download link.

### ISSUE THREAD

**Issue by zackees** [sinedie/SRTranslator#52]
Hi I ran into this bug about a month ago (haven't tried to repro it since).

The bug is in the `webdriverdownload` dependency that fails to find the download link for the chrome driver when on mac m1 due to the way the download url is constructed, which will 404 on the mac m1.

A proper fix ideally would be applied in the webdriverdownload dependency itself. However there is an explicit override that could be used at your layer to set the download link explicitly. The x86 version should work with the Mac M1 arm processor.

Another fix would be to use my package called https://github.com/zackees/open-webdriver which has automated platform tests to ensure proper functioning on all platforms.

Thank you for an excellent library. I use it extensively.

**Comment by sinedie** [comment]
Hey. Yeah, some people are having trouble with the driver download. This weekend I'll check your package and probably make a patch.

Thank you for using it :D

**Comment by sinedie** [comment]
Ok, I'm back.

I took a look on your repo and it is really easy to use, but I don't think I'll use it, at least yet. This is why:

1. I really can't see if you are downloading the driver on each run -Are your are saving that [file](https://github.com/zackees/open-webdriver/blob/ebc07a83d064b1b6bb1b86eccf4b963d8cdc9743/open_webdriver/download_chromium.py#L87)?-
2. There is no simple way to set a proxy to the driver without changing some code, and proxy is a must

It think we could solve this issues if you wanna.

**Comment by zackees** [comment]
It should only download once. Are you seeing it download multiple times?

Your status quo solution almost works, you can just override the download link by monkey patching sys.machine or whatever is being used to determine the CPU type so that it returns x86 on mac.

**Comment by sinedie** [comment]
Hey, sry for the late reply.

Maybe you could create your own custom chrome driver and pass it to DeepLTranslator. No need to use the firefox one.

You still get all the benefits of this package. Just need a way to rotate the proxy to avoid getting banned if you use it in a really large file.
