### ISSUE TITLE
question about srt_file.py

### ISSUE THREAD

**Issue by toprak** [sinedie/SRTranslator#55]
I have deepl pro account for website not api I somehow managed to make deepl_scrap work with it, since it has no limit I changed 1500 to random stuff I wonder, still would I get benefits of srt_file.py talking about that merging stuff that with - . dont remember tbf

**Comment by sinedie** [comment]
Hey, nice you made it work (yeah, only put a really big number on character limit -this would do unnecessary comparsions but, who cares, not too much time is wasted-)

Yeah, the core of this package is that file. The rest of it is just a plus. Even if you create your own translator it will handle that situation and also wrapping lines.

Again: This is an utility to convert srt files to simple text to translate with a provider and back to an srt file, not a translator itself.
