### ISSUE TITLE
DeeplTranslator timeout

### ISSUE THREAD

**Issue by callista13** [sinedie/SRTranslator#56]
Hi, I used to be able to make the GUI work fine, but it's suddenly stopped working.

... Translating chunk. 0 %
Error al traducir el archivo <filepath>: Translation timed out

**Comment by toprak** [comment]
I translated subtitles that worths 5 hours in 1 hour with deepl-scrap, cant replicate.

**Comment by sinedie** [comment]
DeepL changed the limit of characters to translate. Need to update this library so the GUI keeps working.

**Comment by toprak** [comment]
@sinedie again? it was 1500 today?

**Comment by sinedie** [comment]
No, it went from 3000 to 1500
