### ISSUE TITLE
Line Seperator

### ISSUE THREAD

**Issue by venomousraid** [sinedie/SRTranslator#58]
Hello, first of all, thank you very much. It will really help me, but I think it is missing a feature. It is absolutely necessary to have a line separator. Because it obviously translates each line separately and thus cannot translate fragmented sentences (ie a sentence divided into two lines) correctly. There are deviated sentences. How can we fix this?

**Comment by sinedie** [comment]
Hey, sry for the late reply... I understand this but is kind of hard to do it. We would need to use NLP to know where the sentences end.

Gonna check if it is possible. Dont promise anything.

**Comment by toprak** [comment]
Doesn't that drain computer resources?

**Comment by sinedie** [comment]
Would be nice but it gets out of scope of this project, so won't fix
