### ISSUE TITLE
Selenium couldn't find the element

### ISSUE THREAD

**Issue by cybaj** [sinedie/SRTranslator#60]
here is the error message.
```
Timed out trying to get element (CLASS_NAME = lmt__source_textarea)
```
[related code](https://github.com/sinedie/SRTranslator/blob/master/srtranslator/translators/selenium_utils.py#L87).

**Comment by mngyuan** [comment]
You can just run it again a few times until it works - I just translated 48min of `en` subtitles to `zh` after getting this error 3 times. this is likely due to differences in rendering time for the elements on the page and the source textarea not rendering in by the time selenium looks for it.

**Comment by bi-pixel** [comment]
I get this error very often. Sometimes you have to start the translation 5 times until it works without problems.

**Comment by sinedie** [comment]
Gonna check this out this week and come back with a solution

**Comment by sinedie** [comment]
Last commit (already on PyPi), may fix this. Feel free to close the issue if it does.

**Comment by h9052300** [comment]
I had the same case.

**Comment by bi-pixel** [comment]
> Last commit (already on PyPi), may fix this. Feel free to close the issue if it does.

After the update, a new error appeared. 
Timed out trying to get element (CLASS_NAME = lmt__language_select--source)

**Comment by sinedie** [comment]
Updated again... css selectors changed by xpath...
