### ISSUE TITLE
Continue translation feature

### ISSUE THREAD

**Issue by MrCalv1n** [sinedie/SRTranslator#63]
It would be great if it were possible to create a feature to save the content that has already been translated in a temporary file so that if the translation fails halfway through, it would be possible to pick up where you left off. 

For long translations there's a chance that it will fail halfway through and then you have to start all over again.

**Comment by sinedie** [comment]
I like it... I'll work on it when I got some time

**Comment by sinedie** [comment]
Fixed in #64 version 0.3.0
