### ISSUE TITLE
TimeOutException("Translation timed out")

### ISSUE THREAD

**Issue by Over7oader** [sinedie/SRTranslator#67]
Hello, after updating to the latest version of the code, I keep getting this error

Loading C:\AI\Translate\srtranslator\pliki\sample.srt
Backup file found = C:\AI\Translate\srtranslator\pliki\sample.srt.tmp
Starting from subtitle 0
... Translating 0 %
Saving C:\AI\Translate\srtranslator\pliki\sample.srt.tmp
Traceback (most recent call last):
  File "C:\AI\Translate\SRTranslator\srtranslator\__main__.py", line 111, in <module>
    srt.translate(translator, args.src_lang, args.dest_lang)
  File "C:\AI\Translate\SRTranslator\srtranslator\srt_file.py", line 181, in translate
    translation = translator.translate(
                  ^^^^^^^^^^^^^^^^^^^^^
  File "C:\AI\Translate\SRTranslator\srtranslator\translators\deepl_scrap.py", line 159, in translate
    return self.translate(text, source_language, destination_language)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AI\Translate\SRTranslator\srtranslator\translators\deepl_scrap.py", line 162, in translate
    raise TimeOutException("Translation timed out")
srtranslator.translators.base.TimeOutException: Translation timed out
WARNING:urllib3.connectionpool:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002A6E34F2BD0>: Failed to establish a new connection: [WinError 10061] Nie można nawiązać połączenia, ponieważ komputer docelowy aktywnie go odmawia')': /session/a344ce3f-4058-41a0-bd8d-26c23b193320
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002A6E34F1750>: Failed to establish a new connection: [WinError 10061] Nie można nawiązać połączenia, ponieważ komputer docelowy aktywnie go odmawia')': /session/a344ce3f-4058-41a0-bd8d-26c23b193320
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002A6E34F05D0>: Failed to establish a new connection: [WinError 10061] Nie można nawiązać połączenia, ponieważ komputer docelowy aktywnie go odmawia')': /session/a344ce3f-4058-41a0-bd8d-26c23b193320

I have already reinstalled the repository several times but it has not helped. I should add that if I add the -s switch to the command, the code goes to the deepl page and correctly enters the text up to the maximum value, but when it does, nothing happens. I am very sorry for the problem and most likely my ignorance I would be grateful for your help :)

**Comment by Over7oader** [comment]
[geckodriver.log](https://github.com/sinedie/SRTranslator/files/12936900/geckodriver.log)

**Comment by sinedie** [comment]
Hey there can you provide the srt file to try to reproduce?... Maybe it has some unexpected character that break the traslator??

**Comment by Over7oader** [comment]
Yeah right, I changed the extensions to txt because I couldn't upload the srt file here. I would also like to say that before the last update your code was working for me
[1 (2).txt](https://github.com/sinedie/SRTranslator/files/13031184/1.2.txt)
[2.txt](https://github.com/sinedie/SRTranslator/files/13031186/2.txt)

**Comment by sinedie** [comment]
Last commit, v-0.3.2 should fix it
