### ISSUE TITLE
Google Colab

### ISSUE THREAD

**Issue by andrewCOL1** [sinedie/SRTranslator#70]
Hey, I'm interested in using this in google colab. Can you give me some tips how to set up this in colab?
Thank you!

**Comment by sinedie** [comment]
Hey, I haven't really used Colab, but this is a really simple package that can use any translator, not only DeepL.

If you wanna use it with the default translator, the selenium-deepl bot, you should get firefox -geckodriver- installed in google colab -idk if thats possible-.

You could use translatepy version, or deepl api or even create your custom translator (**read the readme and docs**). This is really just an utility to read, reorganize, slice and pass the result to a translator. Then save the result. This is not a traslator, and dont use more than SRT package to work, other stuff are just to make it easy to final user.

**Comment by andrewCOL1** [comment]
Thanks for reply.
