### ISSUE TITLE
Why module is not working from cmd?

### ISSUE THREAD

**Issue by eXpressionist** [sinedie/SRTranslator#74]
![image](https://github.com/sinedie/SRTranslator/assets/5430284/b9fe2609-2492-43a5-ba84-f1ef88fef5a5)
Somehow after last update srtranslator stopped working from command shell, but works fine from IDE. 
What could be a problem? I've tried to reinstall python and cleaned all site-packages, but it doesn't help.

**Comment by k-aito** [comment]
I just give it a try and on my side I have the `--debug` flag working at least.
By reading the code, I don't see anything missing.
You can maybe try to install the software in a virtual environment to see if you can reproduce the issue.

**Comment by k-aito** [comment]
Yes, I could have understood if my PR had broken something because I modified the file used by the cmd but if I understand properly, it still works with my PR applied?

The other PR applied is about the proxy, but the code looks completely fine in my opinion and I don't see why the debug would not be displayed on Windows.

I admin I feel a bit lost too ^^

**Comment by sinedie** [comment]
Can't replicate, just uninstalled and reinstalled the package and ```python -m srtranslator -h``` works out of the box.

The only thing #72 did was to import deeplx, maybe your python version have a problem with this package?

**Comment by eXpressionist** [comment]
> The only thing #72 did was to import deeplx, maybe your python version have a problem with this package?

I don't know how to inspect this, if you have suggestions, it'll be appreciated. 

The thing is - it works from IDE, as I've mentioned in first post. So most confusing part to me, why it doesn't give any output in CMD.

**Comment by k-aito** [comment]
You can maybe try to add some print command in https://github.com/sinedie/SRTranslator/blob/master/srtranslator/__main__.py to see if it read the file.

From the IDE, you don't use the __main__.py file directly, that's why I think the problem could only be with the file.

**Comment by eXpressionist** [comment]
> to see if it read the file.
Yeah, It seems I found the root of the problem. 
In main.py I've added prints after each import. And it doesn't showed me one after `from .translators.pydeeplx import DeepLX`
it's definetly because of it, because Python 3.12 couldn't execute ` from PyDeepLX import PyDeepLX`

So then I'll try to bother developer of this module :)
Thank you, guys.

**Comment by k-aito** [comment]
I would never have thought that it would silently fail good finding!
It is true, my python is still 3.10

**Comment by eXpressionist** [comment]
> that it would silently fail

it gives _Process finished with exit code -1073740791 (0xC0000409)_ when you just execute import from IDE
Usually these type of errors doesn't appear when you run from cmd.
