### ISSUE TITLE
language support

### ISSUE THREAD

**Issue by BanziSeo** [sinedie/SRTranslator#75]
Hello.
I find the project you've created to be very useful. 
However, I am using Korean, and I would like to use this API to translate Korean. 
I am aware that Korean is not currently supported, but I was wondering if there are any plans to support it, or if you could tell me how I can translate it?

**Comment by k-aito** [comment]
Hello, I think it would work. Deepl support Korean and I think SRT support them too. Is there a specific error or issue when you try to do it?

**Comment by sinedie** [comment]
@BanziSeo check in the [docs](https://github.com/sinedie/SRTranslator/blob/master/docs/deepl_scrap.md#supported-languages), DeepL support Korean, so there should be no problem.

Try with this command and check if you get any error
```python -m srtranslator -i ko -o en ./path/to/file```

**Comment by shlifedev** [comment]
I'm Korean, and I have no problem using srtranslator for Korean translation.

**Comment by shlifedev** [comment]
I'm Korean, and I have no problem using srtranslator for Korean translation.

**Comment by sinedie** [comment]
@shlifedev thank you for confirm. Closing this
