### ISSUE TITLE
Is there any way to protect subtitle's sentence structure

### ISSUE THREAD

**Issue by toprak** [sinedie/SRTranslator#76]
input
```
1
00:00:00,000 --> 00:00:06,800
Amy Schumer places first on literally every single list titled Worst or Most Hated Comedians of All Time.

2
00:00:06,940 --> 00:00:07,240
Why?

```
output
```1
00:00:00,000 --> 00:00:06,800
Amy Schumer, Tüm Zamanların En Kötü ya da En
Nefret Edilen Komedyenleri başlıklı her listede
kelimenin tam anlamıyla ilk sırada yer alıyor.

2
00:00:06,940 --> 00:00:07,240
Neden mi?
```
but i think output should be like this
```Amy Schumer, Tüm Zamanların En Kötü ya da En Nefret Edilen Komedyenleri başlıklı her listede kelimenin tam anlamıyla ilk sırada yer alıyor.```
I guess it is done for the 1500 word limit, but I don't know, I would like to discuss it.

**Comment by toprak** [comment]
More precisely, I had to ask the question like this, there is a 1500 character limit, I assume that it translates line by line, let's say that it came to the lines I threw below, and the 1500 word limit ended at the word _comedians_,  does it translates that line, that  the line starting with Amy , in the next 1500 character limit or translate the line till the comedians and rest of the line in next 1500, my goal is to prevent incorrect or incomplete translation When I saw that it gave the output as I threw above, I wondered if this system does not work as I described.(does it translates that line, that  the line starting with Amy , in the next 1500 character limit)
```1
00:00:00,000 --> 00:00:06,800
Amy Schumer places first on literally every single list titled Worst or Most Hated Comedians of All Time.
2
00:00:06,940 --> 00:00:07,240
Why?
```

**Comment by k-aito** [comment]
From my understanding it's related to the wrapping that is set by default at 50 characters.

**Comment by sinedie** [comment]
Thats right, this is related to the wrapping limit. When a sentence exceeds the 1500 char limit it won't be half translated but saved for the next chunk
