### ISSUE TITLE
DeepLx does not use proxy and kills itself

### ISSUE THREAD

**Issue by toprak** [sinedie/SRTranslator#77]
@k-aito 
```C:\Users\godmo>py -m srtranslator "C:\Users\godmo\OneDrive\Desktop\Eyes Wide Shut ENG.srt" -i en -o tr -w 150 -t deeplx
Loading C:\Users\godmo\OneDrive\Desktop\Eyes Wide Shut ENG.srt
... Translating 0 %
...... Wait randomly 4s
...... Exception PyDeepLX Error: Too many requests, your IP has been blocked by DeepL temporarily, please don't request it frequently in a short time. with retry number 3
...... Use or change proxy
...... Exception _ssl.c:989: The handshake operation timed out with retry number 2
...... Use or change proxy
...... Exception PyDeepLX Error: Too many requests, your IP has been blocked by DeepL temporarily, please don't request it frequently in a short time. with retry number 1
...... Use or change proxy
Saving C:\Users\godmo\OneDrive\Desktop\Eyes Wide Shut ENG.srt.tmp
Traceback (most recent call last):
  File "C:\Users\godmo\AppData\Local\Programs\Python\Python311\Lib\site-packages\srtranslator\__main__.py", line 113, in <module>
    srt.translate(translator, args.src_lang, args.dest_lang)
  File "C:\Users\godmo\AppData\Local\Programs\Python\Python311\Lib\site-packages\srtranslator\srt_file.py", line 186, in translate
    translation = translation.splitlines()
                  ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'splitlines'
```

**Comment by k-aito** [comment]
It doesn't use proxy the start. I have some modifications in another branch that give the possibility to enable proxy by default.

https://github.com/k-aito/SRTranslator/commit/abcf2cb24a7eb5f88c1bea60fb7efc0c6614f489

It could be reversed to be enabled by default, I will follow what @sinedie decide. The name change is because I noticed another package that could be used as alternative.

The split error is doesn't fixed for now but running it again will pickup where it stopped.

**Comment by toprak** [comment]
>The split error is doesn't fixed for now but running it again will pickup where it stopped
Okay but it makes hard to use it in robust workflows.
>It doesn't use proxy the start
I know, I thought the splitline error caused by when it switches to use proxy.

**Comment by k-aito** [comment]
At first read, I think the issue is related to result being returned as None even after 10 retry. I think that raising an exception would make a proper exit instead of a trace error.
