### ISSUE TITLE
Timed out trying to get element

### ISSUE THREAD

**Issue by toprak** [sinedie/SRTranslator#8]
I do not know if it was for once or not, there were nothing passed to deepl and I got that error
```
`Timed out trying to get element (XPATH = //button[@dl-test='translator-lang-option-tr'] | //button[text()='Turkish'])`
```

**Comment by sinedie** [comment]
Sadly deepl implemented a modal dialog that hides the input fields. 

![image](https://user-images.githubusercontent.com/43920544/213728312-fb4d146a-af25-4a0c-810c-2f6ae5f4ffd5.png)

It doesn't pop up all the times.

I'll solve it soon, if i have time. Ty for the feedback :D

**Comment by toprak** [comment]
your welcome, can you upload it to pypi please.

**Comment by sinedie** [comment]
Uhh, forgot about it lol. It is done now. v0.1.7
