### ISSUE TITLE
The latest GUI version v2.0.7b keep crashing because of timeout

### ISSUE THREAD

**Issue by h4rdkor1** [sinedie/SRTranslator#80]
The latest version keep crashing while translation and the api version doesnt even start even after having pro api key.

![Screenshot 2024-01-11 000657](https://github.com/sinedie/SRTranslator/assets/21197676/ca6516ec-00c3-4e4d-8b64-49038d0cd34a)

`See the end of this message for details on invoking
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
SrtTranslatorAPI.Translator.TimeOutException: Translation timed out
at SrtTranslatorAPI.Translator.deeplsrap.Translate(String text, String sourceLanguage, String destinationLanguage) in C:\Users\omen\source\repos\SrtTranslatorAPI\SrtTranslatorAPI\Translator\deeplscrap.cs:line 159
at SrtTranslatorAPI.Translator.srtfile.Translate(Translator translator, String sourceLanguage, String destinationLanguage, Int32& progre) in C:\Users\omen\source\repos\SrtTranslatorAPI\SrtTranslatorAPI\srtfile.cs:line 130
at SRTranslatorGUI.Form1.<>c__DisplayClass32_0.b__0() in C:\Users\omen\source\repos\SRTranslatorBeta\SRTranslatorBeta\Form1.cs:line 524
at System.Threading.Tasks.Task.InnerInvoke()
at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at SRTranslatorGUI.Form1.d__32.MoveNext() in C:\Users\omen\source\repos\SRTranslatorBeta\SRTranslatorBeta\Form1.cs:line 507
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at SRTranslatorGUI.Form1.d__21.MoveNext() in C:\Users\omen\source\repos\SRTranslatorBeta\SRTranslatorBeta\Form1.cs:line 170
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.b__6_0(Object state)
Screenshot 2024-01-11 000657

************** Loaded Assemblies **************
mscorlib
Assembly Version: 4.0.0.0
Win32 Version: 4.8.9181.0 built by: NET481REL1LAST_C
CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
SRTranslatorBeta
Assembly Version: 2.0.7.0
Win32 Version: 2.0.7.0
CodeBase: file:///C:/Users/desig/OneDrive/Desktop/SRTranslator.v2.0.7b/SRTranslatorBeta.exe
System.Windows.Forms
Assembly Version: 4.0.0.0
Win32 Version: 4.8.9181.0 built by: NET481REL1LAST_C
CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
System
Assembly Version: 4.0.0.0
Win32 Version: 4.8.9206.0 built by: NET481REL1LAST_B
CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
System.Drawing
Assembly Version: 4.0.0.0
Win32 Version: 4.8.9032.0 built by: NET481REL1
CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
System.Configuration
Assembly Version: 4.0.0.0
Win32 Version: 4.8.9032.0 built by: NET481REL1
CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
System.Core
Assembly Version: 4.0.0.0
Win32 Version: 4.8.9200.0 built by: NET481REL1LAST_C
CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
System.Xml
Assembly Version: 4.0.0.0
Win32 Version: 4.8.9032.0 built by: NET481REL1
CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
Accessibility
Assembly Version: 4.0.0.0
Win32 Version: 4.8.9032.0 built by: NET481REL1
CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
Newtonsoft.Json
Assembly Version: 13.0.0.0
Win32 Version: 13.0.3.27908
CodeBase: file:///C:/Users/desig/OneDrive/Desktop/SRTranslator.v2.0.7b/Newtonsoft.Json.DLL
System.Numerics
Assembly Version: 4.0.0.0
Win32 Version: 4.8.9032.0 built by: NET481REL1
CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
System.Runtime.Serialization
Assembly Version: 4.0.0.0
Win32 Version: 4.8.9032.0 built by: NET481REL1
CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
System.Data
Assembly Version: 4.0.0.0
Win32 Version: 4.8.9191.0 built by: NET481REL1LAST_C
CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
Microsoft.WindowsAPICodePack.Shell
Assembly Version: 1.1.4.0
Win32 Version: 1.1.4.0
CodeBase: file:///C:/Users/desig/OneDrive/Desktop/SRTranslator.v2.0.7b/Microsoft.WindowsAPICodePack.Shell.DLL
Microsoft.WindowsAPICodePack
Assembly Version: 1.1.4.0
Win32 Version: 1.1.4.0
CodeBase: file:///C:/Users/desig/OneDrive/Desktop/SRTranslator.v2.0.7b/Microsoft.WindowsAPICodePack.DLL
PresentationFramework
Assembly Version: 4.0.0.0
Win32 Version: 4.8.9200.0
CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework/v4.0_4.0.0.0__31bf3856ad364e35/PresentationFramework.dll
WindowsBase
Assembly Version: 4.0.0.0
Win32 Version: 4.8.9200.0 built by: NET481REL1LAST_C
CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/WindowsBase/v4.0_4.0.0.0__31bf3856ad364e35/WindowsBase.dll
PresentationCore
Assembly Version: 4.0.0.0
Win32 Version: 4.8.9200.0 built by: NET481REL1LAST_C
CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/PresentationCore/v4.0_4.0.0.0__31bf3856ad364e35/PresentationCore.dll
System.Xaml
Assembly Version: 4.0.0.0
Win32 Version: 4.8.9200.0 built by: NET481REL1LAST_C
CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xaml/v4.0_4.0.0.0__b77a5c561934e089/System.Xaml.dll
FreeProxy
Assembly Version: 1.0.0.0
Win32 Version: 1.0.0.0
CodeBase: file:///C:/Users/desig/OneDrive/Desktop/SRTranslator.v2.0.7b/FreeProxy.DLL
WebDriver
Assembly Version: 4.0.0.0
Win32 Version: 4.0.0.0
CodeBase: file:///C:/Users/desig/OneDrive/Desktop/SRTranslator.v2.0.7b/WebDriver.DLL
SrtTranslatorAPI
Assembly Version: 1.0.0.0
Win32 Version: 1.0.0.0
CodeBase: file:///C:/Users/desig/OneDrive/Desktop/SRTranslator.v2.0.7b/SrtTranslatorAPI.DLL
System.Net.Http
Assembly Version: 4.0.0.0
Win32 Version: 4.8.9032.0 built by: NET481REL1
CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Net.Http/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Net.Http.dll
HtmlAgilityPack
Assembly Version: 1.11.46.0
Win32 Version: 1.11.46
CodeBase: file:///C:/Users/desig/OneDrive/Desktop/SRTranslator.v2.0.7b/HtmlAgilityPack.DLL
SeleniumExtras.WaitHelpers
Assembly Version: 3.11.0.0
Win32 Version: 3.11.0.0
CodeBase: file:///C:/Users/desig/OneDrive/Desktop/SRTranslator.v2.0.7b/SeleniumExtras.WaitHelpers.DLL
SRT
Assembly Version: 1.0.0.0
Win32 Version: 1.0.0.0
CodeBase: file:///C:/Users/desig/OneDrive/Desktop/SRTranslator.v2.0.7b/SRT.DLL
************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.
`

**Comment by sinedie** [comment]
That GUI is not mine, so I can't warranty that its is working right. You should ask in that repo. If the community ask for a GUI version included in this package, i could manage to integrate it or make another in top of this package.

**Comment by h4rdkor1** [comment]
Hi @sinedie, Thank you for your hard work and response. The GUI version was created by user @KryptoST and I already raised the issue on that repo but there is no response so far. Also in that repo @KryptoST mentioned if you face any problem we should raise it in the original repo as shown in the screenshot below. If you can create a GUI version of the translator many people who dont have proper knowledge of using python like myself will be able to use it and will be very thankful.

https://github.com/KryptoST/SRTranslatorGUI/issues/18

![image](https://github.com/sinedie/SRTranslator/assets/21197676/ee12fb89-6c82-47d2-97a7-635c7d615609)

**Comment by XZTence** [comment]
> That GUI is not mine, so I can't warranty that its is working right. You should ask in that repo. If the community ask for a GUI version included in this package, i could manage to integrate it or make another in top of this package.

Would love to have a GUI version if you could do it. Thanks alot for all the work you do.

**Comment by sinedie** [comment]
@k-aito wonderful. I was planning doing a c++ with SDL GUI, but if we can use Briefcase, better make the GUI in python (could be ezgui -as it is really simple- or Qt, cause it is prettier) and ship it all together.

**Comment by k-aito** [comment]
@sinedie 

I pushed my last stuff in my branch, it's still a work in progress, and it would need to update for the toml to properly set you back as author etc because I had few issues with python version and I just took the default values. I also guess that I did modifications that are no more needed or that there are a better way of doing it ^^

https://github.com/k-aito/SRTranslator/tree/convert-to-briefcase

**Comment by h4rdkor1** [comment]
Hi @k-aito is there any update about the briefcase version of this app

**Comment by k-aito** [comment]
> Hi @k-aito is there any update about the briefcase version of this app

I didn't go further yet, my last try was kind of ok for english -> french with pydeeplx when it was working because they still have their API issue. I didn't really try the selenium part because I have some issues with the geckodriver.

**Comment by h4rdkor1** [comment]
@k-aito Thanks for putting up so much work in this, cant wait to see full working version.

**Comment by sinedie** [comment]
Keep an eye on #83. It works for deepl-scrap but still is a work in progress.

The ideal is to release packages for all mayor systems (windows, linux, mac).

It is an initial aproach, not production ready.

**Comment by sinedie** [comment]
@k-aito I saw that you are "migrating" the original srtranslator cli/script package.

It took another aproach: to keep it as it is and create another package in top of it that only cares of the graphical aspects. This is: a simple gui that calls the original translator. I find this way more flexible and separate the logic from the view.

You could help if you want or finish your version and I'll add a link in the readme for the ones who like your implementation.

Anyway ty all for using this package and collaborate to make it better. Cya

**Comment by k-aito** [comment]
Hello @sinedie 

No problem, like I write in the PR, I'm interested to understood because the way I took was the only one I had in mind.

Like having, it is still working in terminal and having a way to use a GUI, but it is really troublesome. That is also why I used thread to have a kind of async thing, but yes, it's troublesome ^^

**Comment by sinedie** [comment]
In last release tag you can find the new official GUI for windows (.msi) and linux (.deb and .flatpack).
