### ISSUE TITLE
GUI Request

### ISSUE THREAD

**Issue by arlovibre** [sinedie/SRTranslator#82]
Hello. Are you thinking of creating a GUI yourself? I am using KryptoST's GUI, but it does not work properly. I would love to have a GUI that works well. Thank you.

**Comment by sinedie** [comment]
Hey there, I was waiting for the briefcase implementation in #80 . Still, I think I'll make my hands dirty with this and gonna put this on the roadmap.

**Comment by arlovibre** [comment]
> Hey there, I was waiting for the briefcase implementation in #80 . Still, I think I'll make my hands dirty with this and gonna put this on the roadmap.

I am looking forward to seeing this happen. Thank you for the reply. Best wishes 🤍

**Comment by sinedie** [comment]
keep an eye in #83. It works but is a work in progress
