### ISSUE TITLE
GUI version does not work

### ISSUE THREAD

**Issue by unleashed7** [sinedie/SRTranslator#86]
Tried different srt files, different translators (DeepL API and DeepL Scraper), but it just freezes and stops responding indefinitely.

Are there any logs to figure out what's happening?

**Comment by sinedie** [comment]
On windows, linux?

**Comment by bw4518** [comment]
Windows 10 here, same problem.

**Comment by unleashed7** [comment]
> On windows, linux?

Windows version, yes!

The non GUI build worked without a problem.

**Comment by sinedie** [comment]
duplicate of #85, working in a solution in my spare time (too little lately)
