### ISSUE TITLE
Very large amount of network connections

### ISSUE THREAD

**Issue by Qhilm** [sinedie/SRTranslator#99]
When running this, I see python connecting to tens of different IPs in the background: Comcast, cloudflare, aws, us-proxy.org, Charter communications (?), etc.

Is that expected?

**Comment by sinedie** [comment]
Well, this package don't call anything more than free-proxy and deepl.com. (And thats if for the built in translator). It seems connecting to those pages spawn multiple connections to different servers.

The core of the library don't need anything but your custom translator to work, so if you don't trust the built in translator, you could create your own. Or review the code inside deepl translator

**Comment by Qhilm** [comment]
Thanks, that's what I thought, it's the deepl translator... Hmmm, I have to admit, I don't like it. What the heck does it need to connect to comcast?? But I'm definitely not able to build my own, so, complaining is easy. I'll close this, I just wanted to know what the package itself needed. Thanks.

**Comment by sinedie** [comment]
I think this is from us-proxy call... if you can give it your own proxy, maybe the number of connections will be lower

**Comment by Qhilm** [comment]
Would that not be required anymore if one had a deepl API key with sufficient credit?

**Comment by sinedie** [comment]
That's another built in translator and shoudn't open those webpages, so yeah. You could try pydeeplx too, it is free
